# Generated by Django 5.2.5 on 2025-08-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Time",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("stop_time", models.DateTimeField(blank=True, null=True)),
                ("duration", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
