# Generated by Django 5.2.5 on 2025-08-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="time",
            name="duration",
        ),
        migrations.AlterField(
            model_name="time",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
