# Generated by Django 5.2.5 on 2025-08-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_time_duration_alter_time_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="time",
            name="category",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
