# Generated by Django 5.2.5 on 2025-10-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_time_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='stop_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
