# Generated by Django 5.2.5 on 2025-10-12 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_time_stop_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Time',
        ),
    ]
