# Generated by Django 5.2.5 on 2025-10-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktime',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
