# Generated by Django 5.2.5 on 2025-10-19 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_time_created_at_alter_time_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='time',
            options={'verbose_name': 'Focus duration'},
        ),
        migrations.AlterField(
            model_name='time',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 19, 19, 31, 56, 962640)),
        ),
        migrations.AlterField(
            model_name='time',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
