# Generated by Django 5.2.5 on 2025-11-08 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_time_created_at_alter_time_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='time',
            options={'verbose_name': 'Time'},
        ),
    ]
