# Generated by Django 5.2.5 on 2025-11-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_time_created_at_alter_time_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
