# Generated by Django 5.2.5 on 2025-11-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_time_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
