# Generated by Django 5.2.5 on 2025-11-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_profilemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='github_username',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
