# Generated by Django 5.2.5 on 2025-11-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_profilemodel_github_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
