# Generated by Django 5.2.5 on 2025-11-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_profilemodel_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='avatar_url',
            field=models.ImageField(blank=True, null=True, upload_to='path/', verbose_name='img'),
        ),
    ]
